### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mlzzen** [mlzzen/open-nga#1]
- [x] 自动签到
- [ ] 多账号自动签到
- [ ] 签到获得N币
- [ ] 多文件夹收藏
- [x] 表情用标签而不是插入图片
- [ ] 更方便的回复贴条
- [ ] 下方的发帖按钮和刷新按钮
- [x] 帖子跳到版面
- [ ] 用html解析帖子避开nga接口的限制
- [x] 常用的表情
- [x] 草稿箱
- [ ] 热评
- [ ] 贴条-点赞数
- [x] 板块调整
- [x] NG娘
- [x] 外层菜单添加浏览历史选项
- [ ] 浏览历史自动跳转到上次的页数
- [ ] 点赞刷新数
- [x] release自动打包
- [x] 发帖上传的图片宽度太大
- [x] 备注用户
- [ ] 精华区搜索
- [x] 在查看回复那里编辑回复
- [x] 修复[size]解析错误
- [x] 修复[table] colspan解析错误
- [ ] 预加载1页
- [ ] 回复关键词屏蔽
- [ ] 屏蔽关键词防重复，搜索，可删除
- [ ] webdav备份，导入，导出屏蔽关键词，板块收藏等等
- [ ] 屏蔽关键字正则
- [x] 只登录了一个用户时隐藏“已登录1个账户”
- [x] 评分正常显示
- [x] 投票正常显示
- [ ] 默认头像
- [ ] 评论显示评论的内容以及引用
- [ ] 合集里面的搜索
- [x] 调整历史记录最大数
- [x] 账号删除后重启又出现
- [ ] 回到顶部 
- [ ] 改包名
- [ ] 用viewBinding代替ButterKnife
- [x] 短消息解析错误
- [ ] 搜索了，但是没有搜索记录
- [x] 签到可配置是否默认启用
- [ ] 浏览记录搜索
- [ ] 多选图片上传
- [ ] 把fastjson替换成jackson
- [ ] 通过插件同步浏览记录，黑名单，备注等等
- [ ] 关注，取消关注，关注列表
- [ ] 个人资料-状态不对
- [ ] 帖子渲染重新做，用原生组件不用webview

**Comment by xss517** [comment]
帖子内容字体大小调节需求，请更新

**Comment by mlzzen** [comment]
> 帖子内容字体大小调节需求，请更新

目前可以调整帖子内容字体大小，设置里面有

**Comment by nsxsv7** [comment]
求个修复被noimg的图片，目前PC这个脚本很好用https://greasyfork.org/zh-CN/scripts/500299-nga-noimg-fix

**Comment by mlzzen** [comment]
> 求个修复被noimg的图片，目前PC这个脚本很好用https://greasyfork.org/zh-CN/scripts/500299-nga-noimg-fix

可以做，但优先级对我来说不高
